name: AdminApp
options:
  bundleIdPrefix: com.bruges.admin-app
  deploymentTarget:
    iOS: 16.2
targets:
  AdminApp:
    type: application
    platform: iOS
    sources: 
      - AdminApp
    info:
      path: AdminApp/Info.plist
