name: AdminApp
options:
  bundleIdPrefix: com.bruges
  deploymentTarget:
    iOS: 17.0
targets:
  AdminApp:
    type: application
    platform: iOS
    sources: 
      - AdminApp
    info:
      path: AdminApp/Info.plist